social:
  google:
    client-id: ${SOCIAL_GOOGLE_CLIENT_ID}
    client-secret: ${SOCIAL_GOOGLE_CLIENT_SECRET}
  facebook:
    client-id: ${SOCIAL_FACEBOOK_CLIENT_ID}
    client-secret: ${SOCIAL_FACEBOOK_CLIENT_SECRET}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SOCIAL_GOOGLE_CLIENT_ID}
            client-secret: ${SOCIAL_GOOGLE_CLIENT_SECRET}
            scope: profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            client-id: ${SOCIAL_FACEBOOK_CLIENT_ID}
            client-secret: ${SOCIAL_FACEBOOK_CLIENT_SECRET}
            scope: email,public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          facebook:
            authorization-uri: https://www.facebook.com/v12.0/dialog/oauth
            token-uri: https://graph.facebook.com/v12.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v12.0/me?fields=id,name,email,picture
            user-name-attribute: id
